import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/Header";
import PagesTransition from "@/components/PagesTransition";
import StairTransition from "@/components/StairTransition";
import Image from 'next/image';
import { icons } from "lucide-react";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Cristian | Personal Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: [
      '/favicon.ico?v=4',
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PagesTransition>{children}</PagesTransition>
      </body>
    </html>
  );
}

